### ISSUE TITLE
Error in Makefile:390

### ISSUE THREAD

**Issue by kauesena** [ummels/fedraserif#1]
Running `make install` gives me the following error:
` make: *** [Makefile:390: check] Error 1`
Looking at line 390 and at `make install --debug=j` did not help. 

Line 390 is:
`        @! ls $(encdir)/a_*.enc > /dev/null 2>&1 || ! echo -e "Found auto-generated encoding files: $$(ls -m $(encdir)/a_*.enc)\nAdd glyphs to glyphlist, remove these files, and remake." 1>&2`

Trying to compile a tex file using the package gives me "Metric (TFM) file not found. "

**Comment by ummels** [comment]
Have you tried doing what the line suggests, i.e. put all the lines from `enc/a_*.enc` into the `glyphlist`, remove these `enc` files and run `make` again?

**Comment by ummels** [comment]
Also could you post the output of the following script?
```
for f in *.otf; do echo $f; otfinfo -v $f; done
```

**Comment by kauesena** [comment]
> Also could you post the output of the following script?
> 
> ```
> for f in *.otf; do echo $f; otfinfo -v $f; done
> ```

This script gives the following output:
```
-v FSerProA-BookItalic.otf
-v FSerProA-Book.otf
-v FSerProA-MediumIta.otf
-v FSerProA-Medium.otf
-v FSerProA-NormalIta.otf
-v FSerProA-Normal.otf
-v FSerProB-BoldItalic.otf
-v FSerProB-Bold.otf
-v FSerProB-BookItalic.otf
-v FSerProB-Book.otf
-v FSerProB-MediumIta.otf
-v FSerProB-Medium.otf
-v FSerProB-NormalIta.otf
-v FSerProB-Normal.otf
```

**Comment by kauesena** [comment]
> Have you tried doing what the line suggests, i.e. put all the lines from `enc/a_*.enc` into the `glyphlist`, remove these `enc` files and run `make` again?

The contents of the `enc` folder are these:
```
fedraserif-bb.enc     fedraserif-oml.enc  fedraserif-qx.enc   fedraserif-t2c.enc
fedraserif-extra.enc  fedraserif-orn.enc  fedraserif-t1.enc   fedraserif-t5.enc
fedraserif-lgr.enc    fedraserif-ot1.enc  fedraserif-t2a.enc  fedraserif-ts1.enc
fedraserif-ly1.enc    fedraserif-ot2.enc  fedraserif-t2b.enc  fedraserif-x2.enc
``` 
`ls enc/a_*.enc` gives no match.

**Comment by ummels** [comment]
Sorry, it should be `dvips/a_*.enc`.

I don't have the FSerProA fonts, so I guess they contain some other glyphs than the B fonts, for which I have compiled the `glyphlist`.

**Comment by ummels** [comment]
Could you also post the output of `otfinfo -i FSerProB-Normal.otf`?

**Comment by kauesena** [comment]
The output of `otfinfo -i FSerProB-Normal.otf` is:
```
Family:              Fedra Serif B Pro Normal
Subfamily:           Regular
Full name:           FedraSerifBPro-Normal
PostScript name:     FedraSerifBPro-Normal
Preferred family:    Fedra Serif B Pro
Preferred subfamily: Normal
Version:             Version 2.501;PS 002.005;hotconv 1.0.38
Unique ID:           Typotheque.com: FedraSerifBPro-Normal 2006
Description:         The digitally encoded machine readable software for producing the Typefaces licensed to you is copyrighted (c) 2006 Typotheque V.O.F. All rights reserved.
Designer:            Peter Bilak (www.typotheque.com)
Designer URL:        www.typotheque.com
Manufacturer:        Typotheque type foundry
Vendor URL:          www.typotheque.com
Trademark:           Fedra Serif is a registered trademark of Typotheque.com
Copyright:           Copyright (c) 2003-2006 Peter Bilak, Typotheque V.O.F. All rights reserved.
License URL:         http://www.typotheque.com/licensing
License Description: The Typotheque Font Software is protected under domestic and international trademark and copyright law. You agree to identify the Typotheque fonts by name and credit TypothequeÕs ownership of the trademarks and copyrights in any design or production credits.
Vendor ID:           TPTQ
```

**Comment by ummels** [comment]
Okay, then it is an older version of the fonts you have (see the README about Font compatibility).

So in this case, either get a newer version of the fonts or do the following:

1. Remove `glyphlist`
2. Run `make clean all` again. The process should end again end with the error you've observed.
3. Run `./scripts/generate-glyphlist.sh > glyphlist` to create a new `glyphlist`.
4. Run `make clean install`.

**Comment by kauesena** [comment]
Thank you for all your help.  Doing the steps you have outlined gives me the following error after step 4:
```
touch: cannot touch 'dvips/fedraserif.map': No such file or directory
make: *** [Makefile:241: dvips/fedraserif.map] Error 1
```

After running `make clean all` the ` the mentioned file, `dvips/fedraserif.map`,  gets erased. In fact, the whole `dvips` folder.

**Comment by texbouja** [comment]
Hi. 
I have the 2.501 version of the fonts and the same errors as @kauesena. The last hint don't work neither for me. Can you please explain a little much how to generate the  correct _dvips_  folder contents and the _glyphlist_ file for this version. 
Thanks for your time.

**Comment by ummels** [comment]
Hi,
could you try the following:

1. Run `make clean` followed by `make`.
2. Remove the file "glyphlist" and run `./scripts/generate-glyphlist.sh > glyphlist`
3. Run `make clean` followed by `make` again.
4. Run `make check` to make sure there are no more problems.
5. Run `make install`.

**Comment by texbouja** [comment]
Perfectly working. Many thanks.
